name: SnapLink CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine

        env:
          POSTGRES_DB: url_shortner
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Give execute permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Build, Test and Verify Coverage
        run: ./mvnw clean verify
        env:
          DB_URL: jdbc:postgresql://localhost:5432/url_shortner
          DB_USERNAME: postgres
          DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}